config/routes.rb
Rails.application.routes.draw do

  get 'challenges/home_challenges', as: :home_challenges
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :challenges, except: [:destroy]
  resources :articles
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :language, optional: true
  validates :name, :description, :link_git, presence: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :challenges
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :challenges
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show]
  before_action :set_article, only: [:show, :edit]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
      if @articles.save
        redirect_to articless_path
      else
        render :new
      end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:name, :description, :language, :link, :link_git)
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home_challenges, :index ]
  before_action :set_challenge, only: [:show, :edit]

  def home_challenges
  end

  def index
    @challenges = Challenge.all
  end

  def show
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params)
      if @challenge.save
        redirect_to challenges_path
      else
        render :new
      end
  end

  def edit
  end

  def update
  end

  private

  def set_challenge
    @challenge = Challenge.find(params[:id])
  end

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :content)
  end
end

app/controllers/errors_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :show ]
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div class="col-xs-12 col-sm-6">
  <div class="article-card">
    <%= link_to article_path(article) do %>
      <div class="article-card-picture" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdXqxj7yu5jz6bMr7oEesrjv_3v-aRkfvJYjKyQD4txYng75SM9w');">
      <div class="article-card-body">
        <h1><%= article.title %></h1>
        <p><%= article.subtitle %></p>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>


<div class="container">
  <div class="row">
      <%= render @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/challenges/_challenge.html.erb
<table class="challenges-table">
  <caption>Orders</caption>
  <thead>
    <th>Language</th>
    <th>Challenge</th>
    <th>See app</th>
    <th>Check code</th>
  </thead>
  <tbody>
    <% @challenges.each do |item| %>
      <tr>
        <td><%= challenge.language.name %></td>
        <td><%= challenge.name%></td>
        <td><%= link_to "See page", challenge.link, class: 'btn-base' %></td>
        <td><%= link_to "See github code", challenge.link_git, class: 'btn-base' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/challenges/_form.html.erb
<%= simple_form_for(@challenge) do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text%>
    <%= f.association :language, as: :select %>
    <%= f.input :link %>
    <%= f.input :link_git %>

    <div class="flex-side">
      <%= f.button :submit, class: "flex-item btn btn-primary"%>
      <%= link_to 'Go back to list of challenges', challenges_path, class: 'flex-item btn btn-danger' %>
    </div>
  <% end %>

app/views/challenges/edit.html.erb
<h1>Challenges#edit</h1>
<p>Find me in app/views/challenges/edit.html.erb</p>

app/views/challenges/home_challenges.html.erb
<div class="container-view">
  <div class="banner-photo", style="background-image: url('https://s33.postimg.cc/bsudyamyn/jeromemonica.png')">
            <div class="item">
              <%= link_to "Add challenge", new_challenge_path, class: 'btn-base btn-action flashing-red' %>
            </div>
            <div class="item">
              <%= link_to "Solve challenge", challenges_path, class: 'btn-base btn-action flashing-green' %>
            </div>


  </div>
</div>

app/views/challenges/index.html.erb
<div class="cards-container">
    <%= render @challenges  %>
</div>

app/views/challenges/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6 col-xs-offset-3">
    <div class=" form-container">
      <h1>New Challenge</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/challenges/show.html.erb
<h1>Challenges#show</h1>
<p>Find me in app/views/challenges/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
<!--     <%#= stylesheet_pack_tag 'application', media: 'all' %> Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= controller_name %><%= action_name %>">
    <% unless action_name == "home" %>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
    <% end %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_navbar_home.html.erb
<div class="navbar-home navbar-default navbar-static-top">
  <!-- Logo -->
    <div class="navbar-home-item">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", height: 50 %>
      <% end %>
    </div>

<div class="hidden-xs">

          <!-- Links when logged in -->
        <%= link_to "About", "#", class: "navbar-home-item navbar-wagon-link tab" %>
        <%= link_to "Challenges", home_challenges_path, class: "navbar-home-item navbar-wagon-link tab" %>
        <%= link_to "Articles", articles_path, class: "navbar-home-item navbar-wagon-link tab" %>
        <%= link_to "Ranking", "#", class: "navbar-home-item navbar-wagon-link tab" %>
    </div>

        <!-- Avatar with dropdown menu -->
      <% if user_signed_in? %>
    <div class="navbar-home-item hidden-xs">
      <div class="dropdown">
        <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> Salut<%#= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  Salut<%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
          </li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
        </ul>
<!--     <#%= link_to destroy_user_session_path, class: 'btn btn-primary', method: :delete do %>
      <%#= t(".sign_out", default: "Log out") %>
    <#% end %>
 -->
      </div>
    </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-home-item navbar-wagon-link btn-black" %>
    <% end %>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-home-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('https://i.ytimg.com/vi/t0kGRcd-IFY/maxresdefault.jpg')">
    <h1>Error#148</h1>
    <hr>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <%= render 'navbar_home' %>
</div>
  <div class="wrapper">
    About
  </div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-default navbar-static-top">
  <!-- Logo -->
    <div class="navbar-home-item">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", height: 50 %>
      <% end %>
    </div>

    <!-- Right Navigation -->
    <div class="hidden-xs">

          <!-- Links when logged in -->
        <%= link_to "About", "#", class: "navbar-home-item navbar-wagon-link tab" %>
        <%= link_to "Challenges", home_challenges_path, class: "navbar-home-item navbar-wagon-link tab" %>
        <%= link_to "Articles", articles_path, class: "navbar-home-item navbar-wagon-link tab" %>
        <%= link_to "Ranking", "#", class: "navbar-home-item navbar-wagon-link tab" %>
    </div>

        <!-- Avatar with dropdown menu -->
      <% if user_signed_in? %>
    <div class="navbar-home-item hidden-xs">
      <div class="dropdown">
        <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> Salut<%#= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  Salut<%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
          </li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
        </ul>
<!--     <#%= link_to destroy_user_session_path, class: 'btn btn-primary', method: :delete do %>
      <%#= t(".sign_out", default: "Log out") %>
    <#% end %>
 -->
      </div>
    </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-home-item navbar-wagon-link btn-black" %>
    <% end %>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-home-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>